# Generated by Django 2.2.12 on 2021-03-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=250)),
                ('url_hash', models.CharField(max_length=8)),
                ('short', models.CharField(max_length=40)),
            ],
        ),
    ]
